Update documents
yktsr/Text2Frame-MV pull request #116
Opened 2023-12-08 14:13 UTC by HidetoshiKawaguchi

@yktsr Text2Frame本体のヘルプドキュメントと、README.mdを更新しました。
確認をお願いします。

なお、デモのアニメーションgifは、masterブランチへの合流後に以下のものをwikiにアップロードしておきます。
![basic_sample](https://github.com/yktsr/Text2Frame-MV/assets/2325716/ddbfebe2-28f8-4597-8ceb-74c4385bccc1)

これにてdev-220のすべてのイシューは完了の認識です。よろしければmasterにも合流してください。
よろしくお願いします。

2023-12-08 17:36 UTC, yktsr requested changes

2023-12-08 17:36 UTC, yktsr commented on README.md
> +1. プラグインコマンドをテストで実行する
```suggestion
1. プラグインコマンドをテストで実行します
```

2023-12-08 17:36 UTC, yktsr commented on README.md
>  例えば、
今更ですけど、この例は初見だとわかりにくいと思います。（=が演算子で、: が区切り文字だと気づけなくて、<=: みたいに見える）
せめて、\<set: 1, 2\> の方が良くないですかね。
```
<=: 1, 2>
```

2023-12-08 17:36 UTC, yktsr commented on README.md
> +
動作確認テキストへのリンクはあったほうがわかりやすいと思います。
```suggestion
より具体的な書き方のサンプルは、[動作確認用テキスト文例ページ](https://github.com/yktsr/Text2Frame-MV/wiki/動作確認テキスト)を参照してください。
```

2023-12-08 17:39 UTC, yktsr commented
デモのアニメーションgifですが、現状のやつで8.6MBあり、トップページを開く際に遅い原因になってます。
新しいのは9.2MBあり、さらに重いです。少しコマ数か長さをダイエットできないですか？

2023-12-08 18:02 UTC, yktsr requested changes

2023-12-08 18:02 UTC, yktsr commented on README.md
> +（プロジェクトのバックアップは取っておいてください）
Quick Startは、この説明のgifの通りやる気がするので、この注意書きはいらないかなって思います。バックアップを取れって書いて、どうしたらいいかツクラーには伝わるでしょうか？（最初の敷居を上げることにならないか懸念）

書くにしても新規プロジェクトを作って試してくださいとか、試してからから組み込んでください、とかの方が敷居が低い気がします。

2023-12-08 18:02 UTC, yktsr commented on Text2Frame.js
> +// ・画面・ピクチャのオプションのバグを修正 #113
機能追加は雑でもいいですが、修正の場合は利用者が修正の内容に該当するか判断する必要がある（すでに組み込んだものに影響する可能性がある）ので、どんな条件でどんな不具合があるのか、詳細の情報を書いた方が良いです。

例：選択肢の表示において、デフォルトの選択肢をNoneまたはなしに設定しており、選択肢をキャンセルした時の処理に選択肢番号を整数で指定している場合に、選択肢をキャンセルした時の処理が設定されない不具合の修正

ちなみに、2.0.1のときは先頭に番号書いていて、その方が綺麗かも
~~102の時に何も考えてませんでした~~
例：
・#83 変数やスイッチ操作タグを使用する際、操作の対象が1つだけのときかつ操作対象が2桁以上の番号の場合、意図しない範囲指定の操作に変換される不具合の修正

2023-12-09 00:31 UTC, HidetoshiKawaguchi commented on README.md
> +（プロジェクトのバックアップは取っておいてください）
これは私も悩んだのですが、やはり消しておきますか。初期設定だと、イベントコマンドの上書きは発生せずに追加されるので、やり直しが効かないということもないですし。
ここは敷居を下げること優先でいきますか

2023-12-09 00:53 UTC, HidetoshiKawaguchi commented
@yktsr 
> デモのアニメーションgifですが、現行のがすでに8.6MBあり、細い回線ではトップページを開く際に遅い原因になってます。 新しいのは9.2MBあり、さらに重いです。少しコマ数か長さをダイエットできないですか？（まあYoutubeのリンクにしろって話は一理どころかありますけど）

横幅を1000から800に落として、リフレッシュレートの違う以下の２つを作りました。
どっちがいいと思いますか？それかまだ落とすか？


5.8MB
![basic_sample_2](https://github.com/yktsr/Text2Frame-MV/assets/2325716/53314c2f-35b0-4df7-9492-99e8504d94a7)


3.3MB
![basic_sample_5](https://github.com/yktsr/Text2Frame-MV/assets/2325716/acee87f1-fca9-44b1-9c5b-4f466dd7b602)

2023-12-09 00:54 UTC, HidetoshiKawaguchi commented
@yktsr 変更要請を反映したものをPUSHしました。再確認をお願いします。

2023-12-09 12:27 UTC, yktsr commented
@HidetoshiKawaguchi 
一個言い忘れてたんですけど、上のgifで最後に組み込んだイベントを実行する際に、
> 闇のゲームでモンスターと繋がってる城之内の精神まで燃え尽きちゃう！

が、
闇のゲームでモンスターと繋がってる城之内の精神まで燃え尽き
になってるの、テスト実行だけの仕様ですか？

2023-12-09 12:30 UTC, yktsr commented
gifは5.8MB版がいいと思いました。

2023-12-09 12:35 UTC, yktsr requested changes
ポロポロ忘れててアレなんですけど、

https://github.com/Shick1112/Text2Frame-MV/issues/35#issuecomment-1837790723

のコメントは取り込んじゃって良いですか？

2023-12-09 14:34 UTC, HidetoshiKawaguchi commented
@yktsr 
> 闇のゲームでモンスターと繋がってる城之内の精神まで燃え尽き
> になってるの、テスト実行だけの仕様ですか？

これはText2FrameもRPGツクールMZも仕様どおりの動作ですね。
１行が長すぎて行末が切れてるだけです。（ちなみにプラグインとか使えば１行の幅は長く出来るはず）
切れてて気持ち悪いかもしれないけど、Text2Frameはテキストをそのまま入れてるだけだぞってのを表してるから別にいいなと思ってます。それよかテキストのほうをわざわざ改行するほうが気持ち悪いかなと
あと、デモのこの切れていることに気づく人ってほぼいないと思いますし、いたとしてもどうってことはないかとも思ってます。
なにかウィンドウ内に収めたほうがいい明確な理由があればそうしますが、そうでないならこれで行かせてください。

> gifは5.8MB版がいいと思いました。

了解です。それで行きます。

> のコメントは取り込んじゃって良いですか？

すみません。見逃してました。ありがとうございます。先程追記したものをPUSHしました。

2023-12-09 14:37 UTC, yktsr commented
了解です

2023-12-09 14:38 UTC, yktsr commented
README.md のContributorにもURL併記しときますね。

2023-12-10 00:45 UTC, HidetoshiKawaguchi commented
@yktsr すまんンゴ・・・。ボロボロやんな。README.mdにも追記しといた（あと自分のホームページのURLも、クリックで飛ぶように更新した）

2023-12-10 05:25 UTC, yktsr approved these changes
修正おつでした。Approveします。

2023-12-10 05:26 UTC, merged